# Generated by Django 4.2.2 on 2023-07-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
