# Generated by Django 4.2.2 on 2023-07-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
