# Generated by Django 4.2.2 on 2023-07-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_openinghour_from_hour_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('restaurant', 'day', 'from_hour', 'to_hour')},
        ),
    ]
