# Generated by Django 4.2.2 on 2023-07-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_country_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='user',
        ),
    ]
