# Generated by Django 4.2.2 on 2023-07-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_is_ordered_remove_orderedfood_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfood',
            name='price',
        ),
    ]
