# Generated by Django 4.2.2 on 2023-07-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderedfood_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
